global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: otel_collector
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - collector:8889